# Generated by Django 3.1.7 on 2021-11-21 14:51

from django.db import migrations, models
import django.db.models.deletion
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=utils.uploading.upload_function)),
                ('use_in_slider', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Галерея изображений',
                'verbose_name_plural': 'Галерея изображений',
            },
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='kids.CartProduct', verbose_name='Продукты для корзины'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(choices=[('summer', 'Лето'), ('winter', 'Зима'), ('spring весна ', 'Весна'), ('autumn осень ', 'Осень')], default='summer', max_length=100, verbose_name='Сезон одежды'),
        ),
        migrations.DeleteModel(
            name='ImageGallert',
        ),
    ]
